version: '2.2'
services:
  app:
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=db'
    init: true

  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  db:
    build:
      context: ./
      dockerfile: docker/db.dockerfile
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - 'MYSQL_DATABASE=inertia_react'
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=secret'
    ports:
      - '33061:3306'

volumes:
  dbdata:
